### ISSUE TITLE
[1.8.2] There are conflict markers in your generated config files

### ISSUE THREAD

**Issue by jesmores** [BlackJar72/DoomlikeDungeons#1]
chests.cfg as well as the themes config files have conflict markers that look like >>>>> HEAD and <<<<< origin/master - I don't think that was intentional? The dungeons still generate, surprisingly enough, but the loot generation is messed up

**Comment by jesmores** [comment]
Still present in the 1.8.3 release from curse

**Comment by BlackJar72** [comment]
This probably wouldn't have been there until very recently, when it might have been added to versions for 1.8 and 1.6.  I'll fix it.

**Comment by BlackJar72** [comment]
Ok, I see what happened, though I don't know how -- some how the chests file for Minecraft 1.6.4 got merged with the one for 1.7.10 -- I don't know how this happened since I develop for 1.7.10 and then merge that into the 1.6 and 1.8 versions, and don't merge those into the 1.7.10 version.  But I'll change fix it.  I'll have to mention it on the forums too, since people will need to delete the old chests.cfg to make it install.  Thanks for reporting this -- I would never have suspected that being there.

**Comment by BlackJar72** [comment]
There, should be fixed.

**Comment by jesmores** [comment]
did you fix the themes files too? it wasn't just the chests.cfg that had the conflict markers

**Comment by BlackJar72** [comment]
Well, I did now.

**Comment by jesmores** [comment]
Awesome, I'm testing it now - will report back :)

**Comment by jesmores** [comment]
Looks like it worked. Conflict markers are gone, and dungeons are generating as expected.

**Comment by BlackJar72** [comment]
Thanks -- finally.  This was not something I expected to deal with yesterday.
