### ISSUE TITLE
don't spawn any block except spawner and chest

### ISSUE THREAD

**Issue by HaoranWang2000** [BlackJar72/DoomlikeDungeons#10]
mod version 1.11.0,forge version 1.7.10-Forge10.13.4.1614, I got another problem,when using /dldspawn command,don't spawn any block except spawner and chest.
I try to use the default theme configuration,then that would be fine,command works normally,but I just changed mob type,there's no changing about building block setting.

**Comment by BlackJar72** [comment]
I don't have that problem, and I can't imagine how that would happen -- the same code places all the blocks, including chests and spawners.  Was this in a super-flat test world?  Some dungeons don't replace air so that they will merge with caves.  Or, what the dungeon a cave dungeon -- some will have a lot of cave-like areas, usually with smooth stone for walls.  Both of those are intended behavior.

**Comment by HaoranWang2000** [comment]
I created a normally new world and used the spawn command 30~40 times,andcan't find anything.

and about the transcoding,I'm gonna try to make a addon if you allow.Even though I'm not good at english and using translator now,and never study any thing about programing,so if you permit,a very optimistic estimates,3~7 months maybe I could complete.

**Comment by HaoranWang2000** [comment]
![2017-12-19_02 38 29](https://user-images.githubusercontent.com/34648429/34122136-6440136e-e466-11e7-97fd-d4432e3a1fec.png)
Used spawn command a lot of times,didn't spawn anything except chest and spawner.
![2017-12-19_02 39 29](https://user-images.githubusercontent.com/34648429/34122137-64732484-e466-11e7-888d-eeaac2b9b4bd.png)
![2017-12-19_02 41 10](https://user-images.githubusercontent.com/34648429/34122138-64abc064-e466-11e7-8813-75b3c0688e9d.png)
Normal world,used spawn command a lot of times,couldn't find any thing.

**Comment by BlackJar72** [comment]
I'll try to look into it -- but probably not today.  Maybe if I compiled with a newer Forge version?

As for transcoding -- go ahead, I have no problem.  If it works, I might see it as a favor.  I do know that Chinese characters work in the files.  If you can type the Chinese writing in, or cut in pasted it from somewhere, its good.  (I have no idea how people type Chinese on a keyboard; I only know there is a way.)

**Comment by BlackJar72** [comment]
Well, the best explanation I can think of for no blocks being in any dungeons is this: The blocks are not being recognized and stored.  Minecraft turns blocks it doesn't know into air.  The chest and spawner blocks are hard-coded.  All other blocks must be looked-up by name because they can change in config files.  If something is wrong with the look-up, so it doesn't find the block, that would explain it.  The problem is we are using the same Forge version and I don't have this problem, no one else I know of has that problem, so I don't know why you are -- is another mod interfering somehow?

As for the text, if you want to make a unicode parser trying looking at "jaredbgreat.dldungeons.parser.Tokenizer" -- I tried to write a unicode function for that but for some reason the place in the string that was being read did not advance.  I was addding to it, "position++" but it just didn't work for some reason.  I've burned myself out and gotten behind on things I need to do in real life, so I just need to step away from this a bit.  I do want to point out again, if you can put Chinese letters into the file directly it works and you do not need the unicode escape sequences.

**Comment by HaoranWang2000** [comment]
Maybe I could find out why there's nothing spawn.
I couldn't found the loot 1 things,so I tried to use the default chest config and main config,and test like TeetoKaziim's Issue,then the structure just apear,the wall,ceiling,floor,it works.
![2017-12-20_13 35 41](https://user-images.githubusercontent.com/34648429/34193419-953e736a-e58e-11e7-9600-d7f44ca9e8ca.png)
So maybe that's just because chest.cfg or DLDungeonJBG.cfg.
And about the test,the result is loot 1 rare like heal/gear/loot 7.

**Comment by HaoranWang2000** [comment]
About transcoding,I had some misunderstood.
transcoding means from one kind of code to another kind of code.What I wanna say is encoding and decoding,means from string to code and from code to string.

**Comment by HaoranWang2000** [comment]
I discover that with out "" ,if I put space in string.So That inportant but about that I have no idea.

**Comment by HaoranWang2000** [comment]
Maybe just fix it,all the problem with NBTstring will be solved.

**Comment by BlackJar72** [comment]
I do not know what you are trying to say.  As far as I can tell it does work.  It does what it is supposed to do.
