### ISSUE TITLE
Cascading worldgen Lag

### ISSUE THREAD

**Issue by Sheppard22** [BlackJar72/DoomlikeDungeons#14]
Hi. Minecraft 1.12.2, last DoomlikeDungeons's release

25.01 08:22:33 [Server] Server thread/WARN [FML]: Doomlike Dungeons loaded a new chunk (-37, 42  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
25.01 08:22:33 [Server] Server thread/WARN Sheppard moved too quickly! -3.2579431058290993,0.0,10.102049323046003

It pulls you back when it happens. Some mins after:

25.01 08:23:55 [Server] Server thread/WARN [FML]: Doomlike Dungeons loaded a new chunk (17, 75  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
25.01 08:23:56 [Server] Server thread/WARN Sheppard moved too quickly! 10.197706848036674,1.1126548666129281,3.1284985343022527

Now, there are other warnings of cascading worldgen lag but they don't pull you back. It's pretty annoying when it does pulls you back.
(Oh, btw, i was flying in creative on a new world)

**Comment by BlackJar72** [comment]
Well, I take it by "pulls you back" you mean rubber banding?  Time jumping backwards?  If this is the case then it is a real problem -- apparently a new problem based on changes in Minecraft and/or Forge.  This doesn't happen most game versions, and I've never seen it in testing, but I haven't tested extensively on 1.12.2 (just enough to see if its generating).

"Cascading" is misleading, its not a chain-reaction -- by design it builds the entire dungeons at once, and generates new chunks to hold it (i.e., its not usually a chain reaction).  This was a bad design, but it was what I came up with as a new modder and kept it because it worked.  I basically know how to fix this now to generate the Minecraft is supposed to generate.  How soon I have time to get to it I don't know though; its major surgery on the heart of the mod.  But I'll look into re-writing dungeon building (and finding) systems to fix this when I can.

Just to be clear -- this is in Minecraft 1.12.2?

**Comment by Sheppard22** [comment]
Yes, it is! Thanks anyways. Oh, and yes, i jump backwards. I was testing mods because i have a really annoying mob/player freezing problem and i want to catch the mod who's doing it.

**Comment by BlackJar72** [comment]
Actually, I've gone ahead and looked at it.  I have the ability to cache dungeons for per chunk building, but...

My old code that handles the dungeon map was badly written.  It would have to be completely re-written at this point and then changes made though out the rest of the mod to make it work due to some bad habit I had at the time.  Frankly, it would be easier at this point just to write a new mod.  Any fix to this would therefore be in a sequel (which I've been planning), not here.  Doomlike Dungeons I may have finally reached the end of its lifespan.

As for rubber banding, I don't seem to experience it.  It could be the result of interaction with another mod, or could something that happens when played on a remote servers if that's what you were doing (rubber banding being more of a problem there).  I've only test this in single player so I don't know.

Anyway, I'm sorry, I probably won't be able to fix this, and this will probably be the final version of Doomlike Dungeons -- a sequel of some kind may or may not appear at some future time.
