### ISSUE TITLE
Dungeons Generating with Empty Chests

### ISSUE THREAD

**Issue by Boolyman** [BlackJar72/DoomlikeDungeons#17]
Title says it all... 1.12.2 forge 2796.  I will load a new world for testing.... Some dungeons generate normally, then I will travel to the next and all the chests are empty.

**Comment by BlackJar72** [comment]
Something like this happened back in 1.8 when they changed how Minecraft handled coordinates, I'll look into it when I can.

**Comment by BlackJar72** [comment]
Is there anything else about this?  Like, the coords (it was important before)?  Other mods used? Any sign of something going wrong (lag spikes, warnings, etc.)?  So far I can't replicate it.

**Comment by Boolyman** [comment]
I dont know what you want me to tell you exactly.   Yes the dungeons all have coordinates.  Do you want every coordinate of every dungeon in the world?  Your dungeon frequency config option doesnt seem to actually increase dungeon frequency either.  Your config claims that changing the option by +2 will increase the distance between dungeons by double... I have changed the number from 8 DOWN to 5, and still can hardly find any dungeons.  Its happening on my Craft of The Titans - The GOG Remix pack that I put out a few days ago.  Can you take a look at it, just load a normal world (you will need to tp to dimension 0 since thats not where you start).  Once you get to the overworld, if you fly around you will notice that 1) The frequency is way too rare to be correct for the config settings I have.  2) Once you DO find a dungeon most, if not all of the chests will likely be empty.

https://minecraft.curseforge.com/projects/craft-to-the-future-cott-ii

**Comment by BlackJar72** [comment]
No, I just want to know your general location -- about where you first found a dungeon without chests.  It was about a hunch, but probably wrong based on testing I've done since.

**Comment by Boolyman** [comment]
It seems many of the dungeons are in about a 600-1000 radius of spawn... but thats also probably just because thats where people have explored

**Comment by Boolyman** [comment]
Getting a lot of these in my chat the last few days.  Kinda putting a damper on my pack.  Anything I can do to help figure out whats wrong?

![2019-01-12 17_13_24-greenshot](https://user-images.githubusercontent.com/24765883/51079497-97884200-168d-11e9-87bc-251588d276d1.png)

**Comment by BlackJar72** [comment]
I'm planning on trying to get a new version out today or tomorrow -- hopefully compiling against the new Forge will solve this problem.

**Comment by BlackJar72** [comment]
Try the new version in a test world and see if it works.
Alternately, what does you're chests.cfg look like -- it wasn't accidentally overwritten at sometimes was it?

**Comment by Boolyman** [comment]
This is my chest.cfg.  I will update to the new build today, but it may take a few days for me to get multiple testers feedback.  Also, are you positive that your dungeon rarity config is working properly?  I have them set to 5, and they are still super tough to find.


https://pastebin.com/qJNF81BD

**Comment by BlackJar72** [comment]
I have doctors appointments two days in a row now, but I'll try and test this out myself sometimes this week if I can get to it -- what mods do all the modded loots come from.

If they are still hard to find try setting EasyFind to true, that may help -- some may be hidden underground or have small difficult to find entrance otherwise (or you just want to test, have you tried flying underground in spectator mode with night vision?).

**Comment by BlackJar72** [comment]
Also, remember, on existing worlds dungeons will not change once generated.

**Comment by BlackJar72** [comment]
I cannot duplicate this problem.  I have not had a chance to test that exact chests.cfg, which would involve setting things up with all the mods the loot is taken from.  

What I think is happening is that there is a typo somewhere in the chests.cfg (the basic format look OK); the item(s) can't be found and is stored as null, so when chests are being filled hitting this ends dungeon generation with an error without filling any more or adding more entrances.  Just a guess, but it seems likely since this doesn't happen with my chests.cfg.
