### ISSUE TITLE
occasionally seeing dungeons chests spawn but not actual dungeon spawns

### ISSUE THREAD

**Issue by Saereth** [BlackJar72/DoomlikeDungeons#23]
some images to show what I mean
https://imgur.com/a/4zt3k81

we're using DoomlikeDungeons-1.11.5-MC1.12.2

Basically where a dungeon would have spawned there are just empty chests and no generation. Found a cascading worldgen warning in the logs near that area but no other relevant info in the logs files.

This does not always occur, maybe dungeons are still generating, but it is happening, I dont have exact numbers on how often unfortunately

**Comment by BlackJar72** [comment]
I do wonder why you're using 1.11.5 when newer version have all the old features and the same dungeon generation algorithms, but simply add new features and more configurability ... but anyway...

My first thought was are the blocks correct in the config?  But this can't be the case, placing are blocks would still delete other blocks in the volume of the dungeons.  Actually, it looks like this old bug that placed duplicate chests and spawner near 0,0: [https://github.com/BlackJar72/DoomlikeDungeons/issues/10](https://github.com/BlackJar72/DoomlikeDungeons/issues/10)

The problem there was that it actually was building the dungeon correctly be some old code ran using the wrong coordinates (relative to 0,0 in the world rather than 0,0 in the dungeon as it should) and placed the extra chests.  This isn't found in the x,z range 0, 0  to 256, 256 by any chance?  This was fixed -- it shouldn't happen in 1.12.x, if that's the problem.

**Comment by Saereth** [comment]
So twitch launcher says we're on version 1.12.3 but the actual file name is 1.11.5... weird gonna delete that and regrab the latest just to verify thats not the issue,

I do believe the blocks are correct in the configs because the dungeons do spawn fully sometimes . Yes most of the places I saw this occur were within that range so updating it will probably sort it hopefully

**Comment by BlackJar72** [comment]
That sound like a bug in Twitch launcher -- I've never used it so don't really know how it works, but it sounds like its reporting the latest version but not actually using that version.

**Comment by Saereth** [comment]
havent seen this occur anymore, thanks

**Comment by BlackJar72** [comment]
np.
