### ISSUE TITLE
suggestion: loot integration with other mods

### ISSUE THREAD

**Issue by GeminiMarshdevil** [BlackJar72/DoomlikeDungeons#24]
loot integration from these mods in the form of per-configured "special chests" .cfg's ?

heroic armory
spartans weapons
spartans shields
living enchantment
improvable skills
electroblobs wizards
curio
ender crop
grimoire of gaia
hexxit gear
random things
reliquary
rustic
waystones

**Comment by BlackJar72** [comment]
You're supposed to add such things yourself, that's why I made it that way.  Perhaps compatibility code would be needed for a few (all Electrobob's books would flood the loot table if set as one item per book even if you did add them all) -- but I don't know when.

Pre-made configs (like the premade biome lists in my other mod) might work but would have to be handled differently.
