### ISSUE TITLE
Causing registry errors

### ISSUE THREAD

**Issue by BarcodeGIT** [BlackJar72/DoomlikeDungeons#28]
Hi, I am trying to setup an RLCraft server which uses this mod and on attempt to join i get "Fatal missing registry entries" and i looked at the logs and found this: https://pastebin.com/GfvMUJsU and i was wondering if there was a way to fix it

**Comment by BlackJar72** [comment]
The problem is the wrong resource locations are used in the chests.cfg and oceanic_chests.cfg files.  Everything with "gold" should instead have "goldern"; for example "minecraft:gold_sword" should actually be "minecraft:golden_sword."  I have no idea what "variedcommodities:gem_ruby" should be.

This is a problem with the way these files have been edited for the modpack, and is something for the modpack author to fix.  None of the problem gear is in the default version of the config.

**Comment by Shivaxi** [comment]
I am fixing this for RLCraft v2.6.3, thanks
