### ISSUE TITLE
[Question]Is Loot/Mob variety only associated with difficulty?

### ISSUE THREAD

**Issue by KAfable** [BlackJar72/DoomlikeDungeons#8]
Hi,

I was looking for some clarification on how the difficulty system works to modify the dungeon, does it only add additional spawners per room while increasing the loot count/chests? I noticed that by turning down the difficulty, the amount of chests greatly decreased.

I wanted to leave the dungeon difficulty on an easier mode to keep the spawners scarce, but only have very powerful mobs coming from actual spanners (using a combination of ArmorPlus,Thermal Foundation, and Deadly Monster Mobs) while maintaining a larger level of chests. This is because on the higher difficulty, the sheer amount of spawners just caused too much lag due to all of the entity spam.

My current workaround was just replacing all of the default zombie, skeleton, spider, witch, etc. mob names in the configs with the more difficult aforementioned mobs and turning down the difficulty, but this ended up also reducing the amount of chests as well.

I want to have certain pieces of loot be available for progression, but I wasn't sure if there's a way to make sure that the chances of a player of getting that loot is close to guaranteed (aside from just making the dungeon huge, which I already did).

**Comment by BlackJar72** [comment]
The I basically starts with the level of the toughest mob, adds a bonus of one if there is more than one spawner, a bonus of one if its treasure room, a 50% chance of a random bonus of one per chest, another 50% chance for a bonus of 1 per item, and a bonus of one if the theme is set as "hard."  The difficulty setting does not directly effect loot, but does so indirectly by having harder mobs.

The simple answer is have mobs assigned as low level will decrease loot.  You could get a bit better loot by setting each theme to hard, but not much.  What I'd do is changes the chests, too, to make better loot count as low level -- basically mirroring the mobs.  Unfortunately, the **_quantity_** will still be less, and there isn't really a way to change that beyond the light advantage of declaring the theme as "HARD.".

**Comment by KAfable** [comment]
Ok thanks for clarifying! This other question might be a long shot, do you have any plans to possible expose to the loot tables of Doomlike Dungeons so that something like LootTweaker may be able to edit them?

**Comment by BlackJar72** [comment]
Well, probably not -- I don't know anything about LootTweaker or how it works, or when it does those things.  I set things up so that it would be easy to modify loot on its own.  Why do you ask?  Is there something LootTweaker does that this doesn't?  Is it easier to use?  If its made to work with the vanilla-style chests table, this has its own system -- if so it would require something like an add-on to LookTweaker.

I'm not saying I'll do it, but it would probably be easier for me to made the quantities directly configurable or to replace "HARD" with a numeric difficulty value -- if that's what you're wanting to do.

**Comment by BlackJar72** [comment]
Currently the number of item in a basic chest is: 
random.nextInt(2 + (level / 2)) + 2

While a treasure chest has two similar formulas for different loot categories (if places some of all three categoris):
random.nextInt(3 + (level / 3)) + 2   (for non-treasure items), and, 
random.nextInt(3 + (level / 2)) + 2   (for treasure / "loot" items)

There would be several values that could be seen as valid for editing (I suppose the minimum would make most since to start with, though).

The loot lists its own system.

**Comment by BlackJar72** [comment]
Try the new 1.11.0 version, perhaps it will have some features you like.

**Comment by KAfable** [comment]
Thanks!
